import Head from "next/head";
import { Nunito } from "next/font/google";
import Header from '../components/header';
import Hero from '../components/hero';
import Propositos from "../components/propositos";
import Transicion from "@/components/transicion";
import NuestroProposito from "@/components/nuestroProposito";
import ViveProposito from "@/components/viveProposito";
import Rutas from '../components/rutas';
import PropositoEnRuta from '../components/propositoEnRuta';
import Clientes from '../components/clientes'
import Footer from '../components/footer';

const nunito = Nunito({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Propósito Andina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Hero/>
      <Propositos/>
      <Transicion/>
      <NuestroProposito/>
      <ViveProposito />
      <Rutas />
      <PropositoEnRuta />
      <Clientes />
      <Footer />
    </>
  );
}

/*
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
*/